//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Validation
    {
        public int Id { get; set; }
        public System.DateTime stamp { get; set; }
        public int user { get; set; }
        public int spot { get; set; }
        public int type { get; set; }
    
        public virtual Spot Spot1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
